CREATE OR REPLACE PROCEDURE TMS.TMS_STAFFDEBT_DELIVERYCODLST
/*
  Mô tả: store lấy danh sách bảng lưu nợ tiền thu hộ của nhân viên
  Người tạo: hoclenho
  Ngày tạo: 26/12/2020 19:43
*/
(V_OUT                OUT SYS_REFCURSOR,
 V_USERNAMELST        IN  TMS_STAFFDEBT.USERNAME % TYPE DEFAULT NULL,
 V_SHIPMENTORDERIDLST IN  VARCHAR2                      DEFAULT NULL)
  AS
    T_TRUCKDEBTLIMITMONEY     NUMBER(20);
    T_MOTOCYCLEDEBTLIMITMONEY NUMBER(20);
  BEGIN
    T_TRUCKDEBTLIMITMONEY := TMS.GETTMSCONFIGNUMBERVALUE('TRUCKDEBTLIMITMONEY');
    T_MOTOCYCLEDEBTLIMITMONEY := TMS.GETTMSCONFIGNUMBERVALUE('MOTOCYCLEDEBTLIMITMONEY');

    IF (T_TRUCKDEBTLIMITMONEY < 1)
    THEN
      T_TRUCKDEBTLIMITMONEY := 50000000;
    END IF;

    IF (T_MOTOCYCLEDEBTLIMITMONEY < 1)
    THEN
      T_MOTOCYCLEDEBTLIMITMONEY := 30000000;
    END IF;

    OPEN V_OUT FOR
    SELECT USERNAME,
           SUM(TOTALTRUCKCOD) TOTALTRUCKCOD,
           SUM(TOTALMOTOCYCLECOD) TOTALMOTOCYCLECOD,
           CASE WHEN SUM(LIMITVALUETRUCK) > 0 THEN SUM(LIMITVALUETRUCK) ELSE T_TRUCKDEBTLIMITMONEY END LIMITVALUETRUCK,
           CASE WHEN SUM(LIMITVALUEMOTO) > 0 THEN SUM(LIMITVALUEMOTO) ELSE T_MOTOCYCLEDEBTLIMITMONEY END LIMITVALUEMOTO

      FROM (SELECT TMS.TMS_STAFFDEBTDETAIL.USERNAME,
                   SUM(TMS.TMS_STAFFDEBTDETAIL.TOTALCOD) TOTALTRUCKCOD,
                   0 TOTALMOTOCYCLECOD,
                   0 LIMITVALUETRUCK,
                   0 LIMITVALUEMOTO
          FROM TMS.TMS_STAFFDEBTDETAIL
          WHERE EXISTS (SELECT CAST(COLUMN_VALUE AS CHAR(20))
                FROM TABLE (TMS.SPLIT(V_USERNAMELST, ','))
                WHERE COLUMN_VALUE IS NOT NULL
                  AND COLUMN_VALUE = TMS.TMS_STAFFDEBTDETAIL.USERNAME)
            AND TMS_STAFFDEBTDETAIL.CARRIERTYPEID = 2
            AND TMS_STAFFDEBTDETAIL.ISUNLOCKDELIVERY = 0
            AND TMS_STAFFDEBTDETAIL.SHIPMENTORDERID NOT IN (SELECT CAST(COLUMN_VALUE AS CHAR(20))
                FROM TABLE (TMS.SPLIT(V_SHIPMENTORDERIDLST, ','))
                WHERE COLUMN_VALUE IS NOT NULL)
          GROUP BY TMS_STAFFDEBTDETAIL.USERNAME

          UNION ALL

        SELECT TMS.TMS_STAFFDEBTDETAIL.USERNAME,
               0 TOTALTRUCKCOD,
               SUM(TMS.TMS_STAFFDEBTDETAIL.TOTALCOD) TOTALMOTOCYCLECOD,
               0 LIMITVALUETRUCK,
               0 LIMITVALUEMOTO
          FROM TMS.TMS_STAFFDEBTDETAIL
          WHERE EXISTS (SELECT CAST(COLUMN_VALUE AS CHAR(20))
                FROM TABLE (TMS.SPLIT(V_USERNAMELST, ','))
                WHERE COLUMN_VALUE IS NOT NULL
                  AND COLUMN_VALUE = TMS.TMS_STAFFDEBTDETAIL.USERNAME)
            AND TMS_STAFFDEBTDETAIL.CARRIERTYPEID = 1
            AND TMS_STAFFDEBTDETAIL.ISUNLOCKDELIVERY = 0
            AND TMS_STAFFDEBTDETAIL.SHIPMENTORDERID NOT IN (SELECT CAST(COLUMN_VALUE AS CHAR(20))
                FROM TABLE (TMS.SPLIT(V_SHIPMENTORDERIDLST, ','))
                WHERE COLUMN_VALUE IS NOT NULL)
          GROUP BY TMS_STAFFDEBTDETAIL.USERNAME

          UNION ALL

        SELECT MU.USERNAME,
               0 TOTALTRUCKCOD,
               0 TOTALMOTOCYCLECOD,
               SUM(CASE WHEN MU.CARRIERTYPEID = 2 AND
                   MU.LIMITVALUE > 0 THEN MU.LIMITVALUE ELSE 0 END) LIMITVALUETRUCK,
               SUM(CASE WHEN MU.CARRIERTYPEID = 1 AND
                   MU.LIMITVALUE > 0 THEN MU.LIMITVALUE ELSE 0 END) LIMITVALUEMOTO
          FROM MDM.MD_USERDEBTLIMIT MU
          WHERE EXISTS (SELECT CAST(COLUMN_VALUE AS CHAR(20))
                FROM TABLE (TMS.SPLIT(V_USERNAMELST, ','))
                WHERE COLUMN_VALUE IS NOT NULL
                  AND COLUMN_VALUE = MU.USERNAME)
          GROUP BY MU.USERNAME)

      GROUP BY USERNAME;
  END;
